### ISSUE TITLE
Bootstrap-vue, vue-moment integration

### ISSUE THREAD

**Issue by sskorupski** [micobarac/vuejs-typescript-starter#1]
# Thanks
Thanks for your repo ! I failed to find a good starter Vue.js dashboard starter kit on the web based on typescript. Yours was perfect !

I didn't know Vuex and I am really happy for this discovery.

# Futher plugin integration 
So, I have started my own project, adding some additionnal plugin integration such as **Bootstrap-vue and momentJS**. I would be happy to contribute to your project be adding these plugins to your kit.

# Contribution
More specifically, I have met an issue about refreshing my components when I selected language in the top bar, that why I would like to share it to the community.

**Comment by micobarac** [comment]
You're welcome. It's been a while since I've created this test project, just to see if I can make it work.

**Comment by micobarac** [comment]
Dependencies are pretty old, I would be happy if you could help keeping it alive.
