### ISSUE TITLE
Upgrade is done

### ISSUE THREAD

**Issue by micobarac** [micobarac/vuejs-typescript-starter#3]
Hi @sskorupski .

I found some time to upgrade this project using the latest Vue Cli.

I found many obstacles on the way that need to be solved, so please, stay tuned.

**Comment by micobarac** [comment]
Updated to latest Vue.

Not working:

- `yarn build` (bulding for production) - `Cannot read property 'parentCompilation' of undefined` (this seems to be an issue caused by awesome-typescript-loader, using some other TS loader might fix the problem)
- Responsiveness is a bit messy, but the template tidiness was not the point here (making Vue work with typescript was the main goal!). User can choose whatever the template he/she wants.

To do:

- update to latest Paper Dashboard template, if necessary: [https://www.creative-tim.com/product/paper-dashboard](https://www.creative-tim.com/product/paper-dashboard), or implement some other template. I tried upgrading to latest Paper Dashboard template, but the styles changed radically and broke the look of template, and I don't have that much time to fix those styles.
- setting [publichPath](https://cli.vuejs.org/config/#publicpath) for production, if published project goes to a subfolder on production server

**Comment by micobarac** [comment]
Fixed `yarn build` (bulding for production) by switching from awesome-typescript-loader to ts-loader in [https://github.com/micobarac/vuejs-typescript-starter/commit/97b6ef0bcf56e366df66fa457009f0cf7bae355f](https://github.com/micobarac/vuejs-typescript-starter/commit/97b6ef0bcf56e366df66fa457009f0cf7bae355f). I don't know why the first loader causes problems, perhaps it should be investigated further.

**Comment by sskorupski** [comment]
Nice work @micobarac  !
I will have some free time this week-end to work on the subject. 

I keep you in touch !
