### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by sskorupski** [micobarac/vuejs-typescript-starter#4]
Since the [Upgraded to lastest Vue](https://github.com/micobarac/vuejs-typescript-starter/commit/0cfa2239f1bf5f39f94002a04addc9679783bf83) commit, I can't start the project anymore.

Did you check that the new version of `package.json` still work installing from a scratch ?

It seems weird that so many devDependencies are no more needed.

Did I missed something ?

**Comment by micobarac** [comment]
I added jquery to avoid Bootstrap warnings and updated the other dependencies a minute ago, and I start the project without problems (it was also working OK before this update), both on macOS and Windows.

![terminal](https://user-images.githubusercontent.com/16001837/53671479-d47cb800-3c7e-11e9-807c-88e99411b5c9.jpg)
![browser](https://user-images.githubusercontent.com/16001837/53671480-d47cb800-3c7e-11e9-941e-e46a74f912c7.jpg)

What is the error you get?

**Comment by micobarac** [comment]
The latest large update was made using vue-cli to generate starter from scratch, then I copied and updated scripts and styles from the previous version. It looks like the newest vue cli doesn't use that much dependencies as it used before.

**Comment by sskorupski** [comment]
My bad !

I deleted my `node_modules` folder and `npm install` followed by `npm run serve` works.

It looks like there was conflicts with the previous dependencies

![My bad](https://media.giphy.com/media/3ohc1ffY03hnhRUyUU/giphy.gif)
