### ISSUE TITLE
vue-google-oauth2

### ISSUE THREAD

**Issue by sskorupski** [micobarac/vuejs-typescript-starter#6]
Hi @micobarac !

Would you appreciate I add [vue-google-oauth2](https://www.npmjs.com/package/vue-google-oauth2)
plugin to the project ?

I suggest to add a ti-user icon at the right of the topbar with the signin label.
When the user click it will trigger the "Google Select account" popup and once the user select the account the signin button is switched by a dropdown with the user name as a label and containing:
* a Signout button
* the setting existing settings button

**Comment by micobarac** [comment]
Sure, anything you find useful.

**Comment by sskorupski** [comment]
Hi, 
I have some difficulties using types definition, I'm wondering if something have to be configured in the `tsconfig.json`. Have a look to:
https://github.com/micobarac/vuejs-typescript-starter/pull/7

Can you have a look to the `google.login.component.ts` ?

**Comment by micobarac** [comment]
What's the error you get? Btw, I suggest adding *types dependencies into dev dependencies, just to differentiate from other packages.

**Comment by sskorupski** [comment]
try after checkout the `feature/vue-google-oauth2` branch

**Comment by micobarac** [comment]
Add `dependencies for types`:

```
yarn add -D @types/gapi
yarn add -D @types/gapi.auth2
```

I guess the `@types/gapi` isn't really necessary, but it's ok to be there.

Edit `tsconfig.ts`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "baseUrl": ".",
    "types": ["webpack-env", "gapi", "gapi.auth2"],
    "paths": {
      "*": ["shims/*"],
      "@/*": ["src/*"]
    },
    "resolveJsonModule": true,
    "lib": ["esnext", "es5", "es2015", "dom", "dom.iterable", "scripthost"]
  },
  "typeRoots": ["node_modules", "node_modules/@types"],
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue", "tests/**/*.ts", "tests/**/*.tsx", "shims/*.d.ts"],
  "exclude": ["node_modules"]
}
```

Edit `google.login.component.ts`:

```typescript
import Vue from 'vue';
import { Component, Prop } from 'vue-property-decorator';
import { namespace } from 'vuex-class';

declare type GoogleUser = gapi.auth2.GoogleUser;
const login = namespace('login');

@Component({
  name: 'GoogleLoginComponent',
  template: require('./google.login.component.html')
})
export class GoogleLoginComponent extends Vue {
  [x: string]: any;

  @Prop({ type: String, default: 'sm' })
  private size!: string;

  @login.Mutation
  private updateGoogleUser!: (googleUser: GoogleUser) => void;

  public signIn(): void {
    this.$gAuth
      .signIn()
      .then(this.onSigninSuccess)
      .catch(this.onFailure);
  }

  public onSigninSuccess(googleUser: GoogleUser): void {
    this.updateGoogleUser(googleUser);
  }

  public onFailure(error: any): void {
    console.error(error);
  }
}

Vue.component('google-login', GoogleLoginComponent);
```

The point is that you cannot import types the way you did, unless they were defined and exported inside of typescript module.

Please, pay attention to the rest of your code on this branch! It contains too many errors for me to handle them all. Please investigate those yourself.

 I strongly suggest that you fix all the warnings and errors that **tslint** suggests. In addition to error handling, I also strongly suggest to install **Prettier** plugin for **VS Code**, if you are using it.

**Comment by sskorupski** [comment]
Thank you a lot, I will have a look in the next week !

Do you have any link where I can read more about the "declare type" syntax ?

The branch is a Work In Progress, I have begun using code from another project I started from the orignal version of this starter project. Since the dependencies update I'm wondering about migrate the other project to the current version of the starter (it could make it cleaner and more up to date :) )

I'm currently using Webstorm with an evaluation version but as far as VS Code  seems to be another good IDE I will try to switch to use it.

**Comment by micobarac** [comment]
You can find a lots of docs on typesript declare command on the net. The fact is that you can use import command only on exported modules installed in node_modules. If you open api.auth2 inside node_modules you can analyze it and only find namespace with declarations inside, and no exported stuff. So, the main rule is that you can import only from exported modules.
